version: '3'

services:
  postgres:
    image: 'postgres:14.0'
    ports:
      - 5433:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notehub
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data
  
  notehub-api:
    build: 
      context: ../notehub-api
      dockerfile: ../notehub-api/app.dockerfile
    ports:
      - 1111:1111
    depends_on:
      - postgres
    env_file:
      - .be.env
    restart: always
    image: notehub-api:latest

  migrate:
    build:
      context: ../notehub-api
      dockerfile: ../notehub-api/migration.dockerfile
    depends_on:
      - postgres
    env_file:
      - .be.env
    restart: "on-failure"
    image: notehub-migrate:latest

  notehub:
    build:
      context: ../notehub-app
      dockerfile: ../notehub-app/app.dockerfile
    ports:
      - 3000:4173
    env_file:
      - .fe.env
    restart: always
    image: notehub:latest